INFERANALYZE= /usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze $(INFER_OPTIONS) -results_dir '/Users/lesiopinheiro/projetos/influunt/influunt-api/infer-out'

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	echo ""

clean:
	rm -f $(CLUSTERS)
