site_name: Influunt Documentação
theme: 'material'
pages:
- Introdução: index.md
- Comunicação:
  - 'Introdução': 'comunicacao/introducao.md'
  - 'Envelope': 'comunicacao/envelope.md'
  - 'Mensagens': 'comunicacao/mensagens.md'  
  - 'Segurança': 'comunicacao/seguranca.md'
  - 'Compactação de Dados': 'comunicacao/gzip.md'
- Protocolos:
  - 'Protocolo de Alto Nível': 'protocolos/alto_nivel/introducao.md'
  - 'Conectividade': 'protocolos/alto_nivel/conectividade.md'
  - 'Ciclo de Vida': 'protocolos/alto_nivel/ciclo_vida.md'
  - 'Configuração do Controlador': 'protocolos/alto_nivel/configuracao.md'
  - 'Transações': 'protocolos/alto_nivel/transacoes.md'
  - 'Alertas e Falhas': 'protocolos/alto_nivel/alertas_e_falhas.md'
  - 'Mudança de Status': 'protocolos/alto_nivel/mudanca_de_status.md'
  - 'Troca de Planos': 'protocolos/alto_nivel/troca_de_planos.md'
  - 'Ler Dados': 'protocolos/alto_nivel/ler_dados.md'  
  - 'Info': 'protocolos/alto_nivel/info.md'  
  - 'Protocolo de Baixo Nível': 'protocolos/baixo_nivel/introducao.md'
- Log:
  - 'Especificação': 'log/especificacao.md'