package protocol;

/**
 * Created by rodrigosol on 9/6/16.
 */
public enum TipoMensagem {
    CONTROLADOR_ONLINE,
    CONTROLADOR_OFFLINE,
    ECHO,
    CONFIGURACAO_INICIAL,
    CONFIGURACAO,
    OK,
    ERRO,
    MUDANCA_STATUS_CONTROLADOR,
    TRANSACAO,
    STATUS_TRANSACAO,
    ENVIO_PLANOS,
    ALARME_FALHA,
    TROCA_DE_PLANO,
    IMPOSICAO_DE_PLANO,
    IMPOSICAO_DE_PLANO_TEMPORARIO,
    REMOCAO_FALHA,
    IMPOSICAO_DE_MODO_OPERACAO,
    LIBERAR_IMPOSICAO,
    LER_DADOS_CONTROLADOR,
    TROCAR_TABELA_HORARIA,
    TROCAR_TABELA_HORARIA_IMEDIATAMENTE,
    TROCAR_PLANOS,
    ATUALIZAR_CONFIGURACAO
}
