package os72c.client.virtual;


import javax.swing.*;
import java.awt.*;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import java.util.logging.Logger;

/**
 * Created by rodrigosol on 11/30/16.
 */
public class LogForm {
    public JTextArea textArea;

    public JPanel form;

    private ConsoleAppender appender;

    public LogForm() {
//        LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();
//        appender = new JTextAreaAppender(lc, textArea);
//        appender.start();

        Logger.getGlobal().addHandler(new Handler() {
            @Override
            public void publish(LogRecord record) {
                System.out.println("publish");
                System.out.println(record);
            }

            @Override
            public void flush() {
                System.out.println("flush");
                //System.out.println(record);
            }

            @Override
            public void close() throws SecurityException {

            }
        });

        //Logger logger = play.api.Logger..getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        form = new JPanel();
        form.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        textArea = new JTextArea();
        form.add(textArea, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return form;
    }
}
